name: CI
env:
  CARGO_TERM_COLOR: always

  PACKAGES_LINUX: libasound2-dev libjack-jackd2-dev libjack-jackd2-0 libdbus-1-dev libpipewire-0.3-dev
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Cache Linux audio packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ${{ env.PACKAGES_LINUX }}
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2.9.1
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: rustfmt
        run: cargo fmt --all --check
  dev-build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Cache Linux audio packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ${{ env.PACKAGES_LINUX }}
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Install target
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --release --bin mavelin-client --target x86_64-unknown-linux-gnu
      - name: Compress
        run: mkdir tmp && cp -r resources tmp && cp target/x86_64-unknown-linux-gnu/release/mavelin-client tmp
      - uses: actions/upload-artifact@v7
        with:
          name: mavelin-client-linux
          path: tmp/**/*
  dev-build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Install target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --release --bin mavelin-client --target x86_64-pc-windows-msvc
      - name: Compress
        run: mkdir tmp && cp -r resources tmp && cp target/x86_64-pc-windows-msvc/release/mavelin-client.exe tmp
      - uses: actions/upload-artifact@v7
        with:
          name: mavelin-client-win
          path: tmp/**/*
  dev-build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Install target
        run: rustup target add x86_64-apple-darwin
      - name: Build
        run: cargo build --release --bin mavelin-client --target x86_64-apple-darwin
      - name: Compress
        run: mkdir tmp && cp -r resources tmp && cp target/x86_64-apple-darwin/release/mavelin-client tmp
      - uses: actions/upload-artifact@v7
        with:
          name: mavelin-client-macos
          path: tmp/**/*
  dev-build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Install target
        run: rustup target add aarch64-apple-darwin
      - name: Build
        run: cargo build --release --bin mavelin-client --target aarch64-apple-darwin
      - name: Compress
        run: mkdir tmp && cp -r resources tmp && cp target/aarch64-apple-darwin/release/mavelin-client tmp
      - uses: actions/upload-artifact@v7
        with:
          name: mavelin-client-macos-arm
          path: tmp/**/*
